version: '2'
services:
    client:
       build:
         context: nginx-php7
         dockerfile: Dockerfile
         args:
           HOST_USER: ${HOST_USER}
           HOST_USER_ID: ${HOST_USER_ID}
           HOST_GROUP: ${HOST_GROUP}
           HOST_GROUP_ID: ${HOST_GROUP_ID}
       ports:
         - ${CLIENT_EXTERNAL_PORT}:80
       volumes:
         - ${CLIENT_REPO_PATH}:/var/www
         - ${CLIENT_LOGS_NGINX_PATH}:/var/log/nginx
         - ${CLIENT_LOGS_PHP_PATH}:/var/log/php-fpm
         - ${HOME_DIR}:/home/${HOST_USER}
       hostname: client
       networks:
         hola_net:
           ipv4_address: 175.27.0.2

    dbmysql:
        image: mysql/mysql-server:5.7
        ports:
            - ${MYSQL_EXTERNAL_PORT}:3306
        volumes:
            - ${MYSQL_LOCAL_PATH}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_HOST: '%'
        hostname: mysql
        networks:
          hola_net:
            ipv4_address: 175.27.0.3
networks:
  hola_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 175.27.0.0/16